### ISSUE TITLE
Have you tried using the MBAPI_x86.dll

### ISSUE THREAD

**Issue by BrianLima** [MinDBreaK/MSI-LED-Control#1]
I'm not 100% sure as i'm not very good at C, but as it seems from what I decompiled the forementioned dll it MIGHT be possible to control motherboard lights using it, I forked and am trying to implement it, maybe you should take a look at it.

**Comment by MinDBreaK** [comment]
No, because I have no idea on how to interact with hardware. But it seems that this dll is designed for x86 CPU only. Any similar DLL around ? Can you also provide the path to this file please ?

**Comment by BrianLima** [comment]
Actually from reading it you don't need to interact with hardware, just with MBAPI, and it will handle things, i'm currently trying to mimic how the MSIGaming APP interacts with it first to then try to understand better and make usable dll.

You can find the file at the original repository: https://github.com/Vipeax/MSI-LED-Tool/tree/master/Lib, try decompiling it with DotPeek and DependecyWalker.

Also, just seems that the DLL runs at x86mode, not only x86 CPUs.

**Comment by BrianLima** [comment]
I got it somewhat working, but I keep getting memory violation errors when trying to use it, i'm trying to look further before making any pull request onto your code, If any.

**Comment by MinDBreaK** [comment]
Hi, can you tell me how your project is ? Have you got some results ?

**Comment by BrianLima** [comment]
I made little progress actually, I can load the mb_api dll on memory, but trying to instantiate any device only throws exceptions left and right, mostly a "Invalid memory address" or something like that, so I think it's possible, but i'm far from it, a bit busy to make more progress sadly.

**Comment by MinDBreaK** [comment]
OK thank you, I'll try to get myself in when i'll have time too.

**Comment by MinDBreaK** [comment]
Maybe you can give a shot at this : http://www.highrez.co.uk/Downloads/InpOut32/default.htm

Plus, you can find all the registers here : https://github.com/nagisa/msi-rgb
