### ISSUE TITLE
What is GC?

### ISSUE THREAD

**Issue by pripishchik** [MinDBreaK/MSI-LED-Control#16]
Readme mentions GC, but what does it mean?

> Updating the LED cause the GC to drop performances for a short time (<0.25s) but result in a short freeze. You should not use temperature based mode during a game. This is related to the librairies and the GC itself. This MIGHT be patched if someone find a way to avoid using MSI libraries.

**Comment by MinDBreaK** [comment]
Hi, 
GC stands for Graphic Card, but it could probably be renamed as GPU to be clearer.
