### ISSUE TITLE
I want to help you developing this app

### ISSUE THREAD

**Issue by ggr18** [MinDBreaK/MSI-LED-Control#2]
Hi. I have a RX480 Gaming X, and I want to help you to succesfully develop the app. If you need testing or something, tell me.

**Comment by MinDBreaK** [comment]
Currently, you can try to compile and check if it's working, but I have the same GC and it's working ;)

But maybe your system can alter the way it works. If you know how to compile yourself the project, pls do and try. If you don't, then I would give you an executable, but for now, I'm a bit busy by the school ^^
