### ISSUE TITLE
NDA_SetIlluminationParm_RGB should be NDA_SetIlluminationParmColor_RGB 

### ISSUE THREAD

**Issue by movrajr** [MinDBreaK/MSI-LED-Control#3]
You'll get a EntryPointNotFoundException because the DLL doesn't have a NDA_SetIlluminationParm_RGB function.

If you change NDA_SetIlluminationParm_RGB into NDA_SetIlluminationParmColor_RGB the program works.

**Comment by MinDBreaK** [comment]
I’ll fix this as soon as I can thanks
