### ISSUE TITLE
UpdateLed uses list index instead of adapter index

### ISSUE THREAD

**Issue by movrajr** [MinDBreaK/MSI-LED-Control#4]
In the LedManager UpdateLed methods, i should be replaced with adapterIndexes[i]. 

Here's an explanation about the current behavior. Let's say you have multiple GPUs:

0 Asus
1 MSI
2 EVGA

Only the MSI GPU is added to the adapterIndexes, so adapterIndexes.Count is 1. Then in the UpdateLed methods the external call to NDA_SetIlluminationParmColor_RGB is sending the list index 0 instead of the expected adapter index 1. The result is that the MSI leds are not affected by this tool.

**Comment by MinDBreaK** [comment]
According to what I have in debug, with only one graphic card, I have 6 adapters. I don’t think this is only related to the graphic card. Hard to know without documentation.

**Comment by movrajr** [comment]
After I changed this:

```cs
for (int i = 0; i < this.adapterIndexes.Count; i++)
{
    _NDA.NDA_SetIlluminationParmColor_RGB(i, ...
}
```

to this:

```cs
for (int i = 0; i < this.adapterIndexes.Count; i++)
{
    _NDA.NDA_SetIlluminationParmColor_RGB(adapterIndexes[i], ...
}
```

the tool works as expected on a machine with multiple NVidia GPUs from different subvendors.

**Comment by MinDBreaK** [comment]
Do you mind doing a pull request ?
