### ISSUE TITLE
Slider for temperature limits

### ISSUE THREAD

**Issue by ggr18** [MinDBreaK/MSI-LED-Control#5]
Add a slider for temperature limits, so you can set your custom temperature margins.

**Comment by MinDBreaK** [comment]
It's not really a slider, but two textboxes. Hope this sweets to you. This will need some testing as I'm not on my personal computer

**Comment by ggr18** [comment]
Yeah, that's ok. I know it's not a bug but a enhancement, but I don't know how to change the flairs.

**Comment by MinDBreaK** [comment]
Yeah I'm the only one who can change it ^^
I just tag it for myself (and the people asking themselves about the issue)

Have you tested it yet ?

**Comment by ggr18** [comment]
No, I haven't had the opportunity to test it since I'm not on my main computer and I can't open it on my actual pc.

The previous build worked as intended on a MSI RX 480 Gaming X 8GB.

**Comment by MinDBreaK** [comment]
No problem, I'll test it as soon as I can.

Just tell me if you have done it before I can

**Comment by ggr18** [comment]
Today I tested it. 

It works, but not really as intended. I need to test it on my other card (a MSI 970 4GB), because the program sets the main clock of the RX480 at top on idle, boosting the temperatures and causing a parcial block if you use any overclock profile. That happens specially if I use "Temperature Based" settings, but has happened twice times with other setting (minor issue, i think).

As I said, I need to test it on another video card.
