### ISSUE TITLE
1080 Gaming Z LED Issue

### ISSUE THREAD

**Issue by MrDexter** [MinDBreaK/MSI-LED-Control#7]
### Expected Behaviour
All lights change when changed in the program including color and effect

### Actual Behaviour
The LEDs on the bottom change with the effect but not color. Backplate stays the same.

### Step to reproduce
Changed colors, effects

### Hardware
MSI GTX 1080 Gaming Z

**Comment by ggr18** [comment]
What light mode/s?

**Comment by MrDexter** [comment]
All, Normally lower LEDs will change with effect and if you try a couple times LED will change but out of sink.  Light color never changes and backplate always stays the same.

**Comment by ggr18** [comment]
I will test it.

**Comment by MinDBreaK** [comment]
Hey ! 
Can you copy/paste the content of the debug window please ? That would help :)

**Comment by MrDexter** [comment]
```PnP Card : 
Vendor Code : N/A
Device Code : N/A
Subvendor Code : N/A
Manufacturer : Nvidia

**Comment by MinDBreaK** [comment]
Ok then, not very helpful xD
I'll have to review this ><

**Comment by ggr18** [comment]
Do you have the latest drivers installed? PnP card sounds like you have not installed any drivers.

Also, what windows version are you running?

**Comment by MinDBreaK** [comment]
Do you have Integrated graphics ? I've seen this sort of thing when I was running it on a computer with IG. 

I'll improve the debug when I'll have time

**Comment by ggr18** [comment]
A copy-paste or a GPU-Z screenshot of the main window would be nice too.

**Comment by MrDexter** [comment]
https://gyazo.com/8a264f26c15149f3802a035b74de29d2

**Comment by MrDexter** [comment]
Latest drivers on Geforce experience are installed. I do have integrated but no drivers are installed for it. (CPU I7 4790K)

**Comment by MinDBreaK** [comment]
Ok !
Well the good news is I that I know why there is nothing in debug. 

The bad news is that I won’t have much time any soon

**Comment by MinDBreaK** [comment]
Can you try the latest commit I added a controller missing. This might fix your issue

**Comment by MrDexter** [comment]
Downloaded the latest release and tried again.  Still the same

PnP Card : 
Vendor Code : N/A
Device Code : N/A
Subvendor Code : N/A
Manufacturer : Nvidia

**Comment by MinDBreaK** [comment]
No I didn't updated the release. You would have to compile on your own. I'll make a release once I fixed the debug

**Comment by MrDexter** [comment]
Sorry for the late reply, How would I go about compiling it myself? Thanks

**Comment by MinDBreaK** [comment]
You need to clone the repo and open the solution (.sln) in Visual Studio 2017/2016.

Then you just need to clic Run in All CPU mode (by default) and Debug mode (by default)

**Comment by MrDexter** [comment]
https://gyazo.com/4843a81fcdfed22e0253cc0b8581741a

**Comment by MinDBreaK** [comment]
I’m working on a fix, but I’m facing some issues when changing color mode. 

I’ll try to fix it to make a release as soon as possible.

**Comment by MinDBreaK** [comment]
I have published a new realease so you should be able to see the debug window
