### ISSUE TITLE
Possible for MSI motherboards?

### ISSUE THREAD

**Issue by ChriscomIT** [MinDBreaK/MSI-LED-Control#9]
Hello, I like the idea and the project. However, I have no MSI graphics card but an MSI mainboard and want to avoid MSI Gaming bloatware. Can you look into supporting MSI mainboards or can you help me to integrate my mainboard cause I need a hint where to start or look for?

Thanks!

**Comment by MinDBreaK** [comment]
I cannot provide yet any implementation for motherboard, you can read more here : https://github.com/nagisa/msi-rgb/

He's working on it, but this is not available for windows as you need a signed kernel driver. 

Also, quoted from ReadMe.md : 

> The control of the motherboard need to communicate with a kernel driver, and I don't know anything about this, but you can read more about this here : https://github.com/nagisa/msi-rgb/

**Comment by ChriscomIT** [comment]
Ok, thanks for the information and providing additional information. I will look into it. But I saw the mentioning of NCT6795D super I/O chip maybe that's the way to go. Yeah I need it for Windows.

Thanks.
